### PR TITLE
Apply autopep8 to all files in the repository

### PR DESCRIPTION
**Pull request by Sol-Mane**

### CODE REVIEW

**Comment by Aemilivs** [comment]
This is going to introduce a lot of conflicts if we are to merge it before PR for #6 
Let's either merge #6 first or rebase this pr against #6

**Comment by Sol-Mane** [comment]
Merged PR #40

**Comment by Sol-Mane** [comment]
Initial pylint report

```
(venv) solmane@domo:~/PycharmProjects/2201-SAD-Bot-Trader$ pylint API/
************* Module API
API/__init__.py:1:0: C0103: Module name "API" doesn't conform to snake_case naming style (invalid-name)
API/__init__.py:1:0: C0114: Missing module docstring (missing-module-docstring)
************* Module API.__main__
API/__main__.py:1:0: C0114: Missing module docstring (missing-module-docstring)
API/__main__.py:9:23: E1120: No value for argument 'trade_tree_service' in constructor call (no-value-for-parameter)
************* Module API.bootstrap
API/bootstrap.py:1:0: C0114: Missing module docstring (missing-module-docstring)
API/bootstrap.py:7:0: C0116: Missing function or method docstring (missing-function-docstring)
API/bootstrap.py:11:4: C0103: Variable name "databaseName" doesn't conform to snake_case naming style (invalid-name)
API/bootstrap.py:13:4: C0415: Import outside toplevel (API.trade_trees.repositories.trade_tree_repository.TradeTreeRepository) (import-outside-toplevel)
API/bootstrap.py:14:4: C0415: Import outside toplevel (API.trade_trees.services.trade_tree_service.TradeTreeService) (import-outside-toplevel)
API/bootstrap.py:15:34: E1120: No value for argument 'configuration' in constructor call (no-value-for-parameter)
API/bootstrap.py:15:34: E1120: No value for argument 'db' in constructor call (no-value-for-parameter)
API/bootstrap.py:16:31: E1120: No value for argument 'configuration' in constructor call (no-value-for-parameter)
API/bootstrap.py:16:31: E1120: No value for argument 'trade_tree_repository' in constructor call (no-value-for-parameter)
API/bootstrap.py:4:0: C0411: standard import "import configparser" should be placed before "from kink import di" (wrong-import-order)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

**Comment by Sol-Mane** [comment]
```
pylint API/

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```

**Comment by Sol-Mane** [comment]
closes #41

**Review by Aemilivs — APPROVED** [review]

**Pull request merged**
